# Generated by Django 2.2.4 on 2020-09-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0076_matchpledge_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpledge',
            name='clr_round_num',
            field=models.ForeignKey(blank=True, help_text='Pledge CLR Round.', null=True, on_delete=django.db.models.deletion.CASCADE, to='grants.GrantCLR'),
        ),
    ]
